from cff2toml.cff2toml import CFFObject, TOMLObject

# loading functions
from cff2toml.loaders import LoadCFFFileException, LoadTOMLFileException
from cff2toml.loaders import load_cff_object, load_toml_object

# saving functions
from cff2toml.savers import SaveCFFFileException, SaveTOMLFileException
from cff2toml.savers import save_cff_object, save_toml_object

# set property functions
from cff2toml.setters import TransformCFFObjectWithTOMLObjectFunction, TransformTOMLObjectWithCFFObjectFunction
from cff2toml.setters import SetCFFPropertyException, SetTOMLPropertyException
from cff2toml.setters import set_object_property
from cff2toml.setters import set_cff_property, set_toml_property
from cff2toml.setters import set_cff_property_with_toml_property, set_toml_property_with_cff_property
from cff2toml.setters import set_cff_with_toml, set_toml_with_cff
from cff2toml.setters import set_citation_cff_with_pyproject_toml, set_pyproject_toml_with_citation_cff
from cff2toml.setters import set_properties_for_cff_and_toml
from cff2toml.setters import set_properties_for_citation_cff_and_pyproject_toml
from cff2toml.setters import set_version_for_citation_cff_and_pyproject_toml


# get property functions
from cff2toml.getters import get_object_property
from cff2toml.getters import get_property_for_citation_cff, get_property_for_pyproject_toml
from cff2toml.getters import get_title_for_citation_cff, get_name_for_pyproject_toml
from cff2toml.getters import get_abstract_for_citation_cff, get_description_for_pyproject_toml
from cff2toml.getters import get_version_for_citation_cff, get_version_for_pyproject_toml
from cff2toml.getters import get_license_for_citation_cff, get_license_for_pyproject_toml
